#!/usr/bin/env bash
set -euo pipefail

# Open Arcana Uninstaller
# Removes Open Arcana files and restores backups

# ── Colors & Styles ───────────────────────────────────────
BOLD=$'\033[1m'
DIM=$'\033[2m'
WHITE=$'\033[1;37m'
CYAN=$'\033[1;36m'
MAGENTA=$'\033[1;35m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[0;33m'
RED=$'\033[0;31m'
DIM_WHITE=$'\033[2;37m'
DIM_CYAN=$'\033[2;36m'
RESET=$'\033[0m'

if [[ ! -t 1 ]] || [[ "${NO_COLOR:-}" != "" ]]; then
  BOLD='' DIM='' WHITE='' CYAN='' MAGENTA=''
  GREEN='' YELLOW='' RED='' DIM_WHITE='' DIM_CYAN='' RESET=''
  NO_ANIM=true
else
  NO_ANIM=false
fi

# ── Terminal helpers ──────────────────────────────────────

term_width() {
  local w
  w=$(tput cols 2>/dev/null || echo 80)
  echo "$w"
}

center_text() {
  local text="$1" width
  width=$(term_width)
  local stripped
  stripped=$(printf '%s' "$text" | sed 's/\x1b\[[0-9;]*m//g')
  local len=${#stripped}
  local pad=$(( (width - len) / 2 ))
  if [[ $pad -lt 0 ]]; then pad=0; fi
  printf '%*s' "$pad" ''
  printf '%s' "$text"
}

center_line() {
  center_text "$1"
  echo ""
}

anim_delay() {
  if ! $NO_ANIM; then
    sleep "${1:-0.04}"
  fi
}

success() { echo -e "  ${MAGENTA}◈${RESET}${DIM}────${RESET} $1  ${GREEN}✓${RESET}"; }
error()   { echo -e "  ${RED}✗${RESET} $1"; }

ray_separator() {
  local w
  w=$(term_width)
  local dots=""
  local count=$(( w / 3 ))
  local i
  for ((i=0; i<count; i++)); do
    dots+="$DIM_CYAN.  $RESET"
  done
  echo ""
  center_line "$dots"
  echo ""
}

# ── Splash ────────────────────────────────────────────────

splash_uninstall() {
  clear 2>/dev/null || true

  echo ""
  echo ""
  echo ""
  echo ""

  local line_text="─────────────────"

  center_line "${DIM_WHITE}o  p  e  n${RESET}"
  center_line "${CYAN}${line_text}${RESET}"
  center_line "${WHITE}${BOLD}a  r  c  a  n  a${RESET}"
  echo ""
  center_line "${DIM_CYAN}Uninstaller${RESET}"

  echo ""
  echo ""
}

# ── Sealed Summary ────────────────────────────────────────

print_sealed() {
  local w
  w=$(term_width)
  local inner=50

  local dot_line=""
  local i
  local dot_count=$(( inner / 2 ))
  for ((i=0; i<dot_count; i++)); do dot_line+=". "; done

  echo ""

  # Animate line contracting (reverse of portal reveal)
  if ! $NO_ANIM; then
    for ((i=dot_count; i>=0; i-=2)); do
      local partial=""
      local j
      for ((j=0; j<i; j++)); do partial+=". "; done
      printf '\r'
      center_text "  ${DIM_CYAN}${partial}${RESET}"
      anim_delay 0.03
    done
    echo ""
    anim_delay 0.2
  fi

  center_line "  ${MAGENTA}${dot_line}${RESET}"
  center_line "  ${MAGENTA}.${RESET}$(printf '%*s' $(( inner - 2 )) '')${MAGENTA}.${RESET}"
  center_line "  ${MAGENTA}.${RESET}      ${WHITE}${BOLD}T H E   V A U L T   I S   S E A L E D${RESET}$(printf '%*s' $(( inner - 43 )) '')${MAGENTA}.${RESET}"
  center_line "  ${MAGENTA}.${RESET}$(printf '%*s' $(( inner - 2 )) '')${MAGENTA}.${RESET}"
  center_line "  ${MAGENTA}${dot_line}${RESET}"

  echo ""
  echo -e "  ${DIM}CLAUDE.md, 00-Dashboard/, and 80-Templates/ were left intact.${RESET}"
  echo -e "  ${DIM}Remove them manually if you no longer need them.${RESET}"
  echo ""
}

# ── Main ─────────────────────────────────────────────────

if [[ $# -lt 1 ]]; then
  echo ""
  echo -e "${BOLD}Usage:${RESET} ./uninstall.sh /path/to/your/vault"
  echo ""
  echo "  Removes Open Arcana files and restores your original settings."
  echo ""
  exit 1
fi

VAULT_PATH="${1/#\~/$HOME}"

if [[ ! -f "$VAULT_PATH/.claude/arcana.config.yaml" ]]; then
  error "No Open Arcana installation found at: $VAULT_PATH"
  exit 1
fi

splash_uninstall

echo -e "  ${DIM}Vault:${RESET} ${BOLD}$VAULT_PATH${RESET}"
echo ""

echo -e "  ${YELLOW}This will remove:${RESET}"
echo "    .claude/rules/ files installed by Open Arcana"
echo "    .claude/hooks/ files installed by Open Arcana"
echo "    .claude/commands/ files installed by Open Arcana"
echo "    .claude/arcana.config.yaml"
echo "    CLAUDE.md (if generated by Open Arcana)"
echo ""

echo -ne "  ${BOLD}Continue? [y/N]${RESET}: "
read -r confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  echo ""
  echo -e "  ${YELLOW}Cancelled.${RESET}"
  echo ""
  exit 0
fi

ray_separator

# Restore settings backup
if [[ -f "$VAULT_PATH/.claude/settings.local.json.bak" ]]; then
  mv "$VAULT_PATH/.claude/settings.local.json.bak" "$VAULT_PATH/.claude/settings.local.json"
  success "Restored settings.local.json from backup"
fi

# Remove arcana config
rm -f "$VAULT_PATH/.claude/arcana.config.yaml"
success "Removed arcana.config.yaml"

# Remove rules that came from Open Arcana
ARCANA_RULES=(
  core-rules.md
  anti-sycophancy.md
  token-efficiency.md
  boot-protocol.md
  connected-sources.md
  domain-example.md
  people.md
  content.md
)

for rule in "${ARCANA_RULES[@]}"; do
  if [[ -f "$VAULT_PATH/.claude/rules/$rule" ]]; then
    rm -f "$VAULT_PATH/.claude/rules/$rule"
  fi
done
success "Removed Open Arcana rules"

# Remove hooks
ARCANA_HOOKS=(
  session-scan.sh
  read-alerts.sh
  enforce-daily-note.sh
  validate-frontmatter.sh
  validate-write.sh
  stop-check-dn.sh
  memory-injection-scan.sh
  cascade-check.sh
  guard-people.sh
  memory-nudge.sh
  prefetch-context.sh
)

for hook in "${ARCANA_HOOKS[@]}"; do
  if [[ -f "$VAULT_PATH/.claude/hooks/$hook" ]]; then
    rm -f "$VAULT_PATH/.claude/hooks/$hook"
  fi
done
success "Removed Open Arcana hooks"

# Remove commands directory if it was created by us
if [[ -d "$VAULT_PATH/.claude/commands" ]]; then
  rm -rf "$VAULT_PATH/.claude/commands"
  success "Removed Open Arcana commands"
fi

# Remove vault-test.sh
if [[ -f "$VAULT_PATH/.vault-test.sh" ]]; then
  rm -f "$VAULT_PATH/.vault-test.sh"
  success "Removed vault-test.sh"
fi

print_sealed
