#!/usr/bin/env bash
set -euo pipefail

# Open Arcana Uninstaller
# Removes Open Arcana files and restores backups

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[1;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

if [[ $# -lt 1 ]]; then
  echo "Usage: ./uninstall.sh /path/to/your/vault"
  echo ""
  echo "Removes Open Arcana files and restores your original settings."
  exit 1
fi

VAULT_PATH="${1/#\~/$HOME}"

if [[ ! -f "$VAULT_PATH/.claude/arcana.config.yaml" ]]; then
  echo -e "${RED}No Open Arcana installation found at: $VAULT_PATH${RESET}"
  exit 1
fi

echo ""
echo -e "${CYAN}Open Arcana Uninstaller${RESET}"
echo ""
echo -e "  Vault: ${BOLD}$VAULT_PATH${RESET}"
echo ""

# Read config to know what was installed
echo -e "  ${YELLOW}This will remove:${RESET}"
echo "    - .claude/rules/ files installed by Open Arcana"
echo "    - .claude/hooks/ files installed by Open Arcana"
echo "    - .claude/commands/ files installed by Open Arcana"
echo "    - .claude/arcana.config.yaml"
echo "    - CLAUDE.md (if generated by Open Arcana)"
echo ""

echo -ne "  ${BOLD}Continue? [y/N]${RESET}: "
read -r confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  echo -e "  ${YELLOW}Cancelled.${RESET}"
  exit 0
fi

echo ""

# Restore settings backup
if [[ -f "$VAULT_PATH/.claude/settings.local.json.bak" ]]; then
  mv "$VAULT_PATH/.claude/settings.local.json.bak" "$VAULT_PATH/.claude/settings.local.json"
  echo -e "  ${GREEN}✓${RESET} Restored settings.local.json from backup"
fi

# Remove arcana config
rm -f "$VAULT_PATH/.claude/arcana.config.yaml"
echo -e "  ${GREEN}✓${RESET} Removed arcana.config.yaml"

# Remove rules that came from Open Arcana
# (we only remove known Open Arcana rule files, not user-created ones)
ARCANA_RULES=(
  core-rules.md
  anti-sycophancy.md
  token-efficiency.md
  boot-protocol.md
  connected-sources.md
  domain-example.md
  pessoas.md
  content.md
)

for rule in "${ARCANA_RULES[@]}"; do
  if [[ -f "$VAULT_PATH/.claude/rules/$rule" ]]; then
    rm -f "$VAULT_PATH/.claude/rules/$rule"
  fi
done
echo -e "  ${GREEN}✓${RESET} Removed Open Arcana rules"

# Remove hooks
ARCANA_HOOKS=(
  session-scan.sh
  read-alerts.sh
  enforce-daily-note.sh
  validate-frontmatter.sh
  validate-write.sh
  stop-check-dn.sh
  memory-injection-scan.sh
  cascade-check.sh
  guard-pessoas.sh
  memory-nudge.sh
  prefetch-context.sh
)

for hook in "${ARCANA_HOOKS[@]}"; do
  if [[ -f "$VAULT_PATH/.claude/hooks/$hook" ]]; then
    rm -f "$VAULT_PATH/.claude/hooks/$hook"
  fi
done
echo -e "  ${GREEN}✓${RESET} Removed Open Arcana hooks"

# Remove commands directory if it was created by us
if [[ -d "$VAULT_PATH/.claude/commands" ]]; then
  rm -rf "$VAULT_PATH/.claude/commands"
  echo -e "  ${GREEN}✓${RESET} Removed Open Arcana commands"
fi

# Remove vault-test.sh
if [[ -f "$VAULT_PATH/.vault-test.sh" ]]; then
  rm -f "$VAULT_PATH/.vault-test.sh"
  echo -e "  ${GREEN}✓${RESET} Removed vault-test.sh"
fi

echo ""
echo -e "${GREEN}Uninstall complete.${RESET}"
echo -e "${DIM}Note: CLAUDE.md, 00-Dashboard/, and 80-Templates/ were left intact.${RESET}"
echo -e "${DIM}Remove them manually if you no longer need them.${RESET}"
echo ""
